### ISSUE TITLE
IndentationError: unindent does not match any outer indentation level

### ISSUE THREAD

**Issue by timruning** [Anton1o-I/thompson-sampling#15]
I run the code 
`from thompson_sampling.bernoulli import BernoulliExperiment
`
meets error :

```
Traceback (most recent call last):

  File "/Users/abc/APP/env/python/anaconda3/envs/tensorflow/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3267, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-5-7daf92b76ade>", line 1, in <module>
    from thompson_sampling.bernoulli import BernoulliExperiment

  File "/Users/abc/APP/env/python/anaconda3/envs/tensorflow/lib/python3.6/site-packages/thompson_sampling/bernoulli.py", line 13
    def __init__(self, arms: int = None, priors: BetaPrior = None, labels: list = None):
                                                                                        ^
IndentationError: unindent does not match any outer indentation level
```

**Comment by Anton1o-I** [comment]
@timruning I just updated the pypi package distribution, please let me know if that doesn't solve the problem. This error was corrected in the repo previously but was never updated in PyPi.
